<a href="https://colab.research.google.com/github/hari-19/Regression_Neural_Networks/blob/master/Regression_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#This Code uses L-1 Layers of Sigmoid and 1 layer of Linear Function.

#The ReLU function is been commented to act as a Linear function, Since, the dataset doesn't require a ReLU function.

#The Cost is computed using Squared Error function.

In [0]:
import numpy as np
import pandas as pd
from google.colab import files
import io

In [0]:
#Data Set needs to be Loaded

# uploaded = files.upload()

In [0]:
# for fn in uploaded.keys():
#   print('User uploaded file "{name}" with length {length} bytes'.format(
#       name=fn, length=len(uploaded[fn])))
# uploaded

In [580]:
url = "https://raw.githubusercontent.com/hari-19/Regression_Neural_Networks/master/AirQualityUCI.csv"
# df = pd.read_csv(io.BytesIO(uploaded[url]))
df = pd.read_csv(url)
print(df)

      CO(GT)  PT08.S1(CO)  NMHC(GT)  ...      AH  Unnamed: 13  Unnamed: 14
0        2.6         1360       150  ...  0.7578          NaN          NaN
1        2.0         1292       112  ...  0.7255          NaN          NaN
2        2.2         1402        88  ...  0.7502          NaN          NaN
3        2.2         1376        80  ...  0.7867          NaN          NaN
4        1.6         1272        51  ...  0.7888          NaN          NaN
...      ...          ...       ...  ...     ...          ...          ...
9352     3.1         1314      -200  ...  0.7568          NaN          NaN
9353     2.4         1163      -200  ...  0.7119          NaN          NaN
9354     2.4         1142      -200  ...  0.6406          NaN          NaN
9355     2.1         1003      -200  ...  0.5139          NaN          NaN
9356     2.2         1071      -200  ...  0.5028          NaN          NaN

[9357 rows x 15 columns]


In [0]:
dfNumpy = df.to_numpy()

In [582]:
dfNumpy

array([[ 2.600e+00,  1.360e+03,  1.500e+02, ...,  7.578e-01,        nan,
               nan],
       [ 2.000e+00,  1.292e+03,  1.120e+02, ...,  7.255e-01,        nan,
               nan],
       [ 2.200e+00,  1.402e+03,  8.800e+01, ...,  7.502e-01,        nan,
               nan],
       ...,
       [ 2.400e+00,  1.142e+03, -2.000e+02, ...,  6.406e-01,        nan,
               nan],
       [ 2.100e+00,  1.003e+03, -2.000e+02, ...,  5.139e-01,        nan,
               nan],
       [ 2.200e+00,  1.071e+03, -2.000e+02, ...,  5.028e-01,        nan,
               nan]])

In [0]:
X = dfNumpy[:,0:12]
X = np.transpose(X)

In [584]:
print(X)
print(np.shape(X))

[[   2.6    2.     2.2 ...    2.4    2.1    2.2]
 [1360.  1292.  1402.  ... 1142.  1003.  1071. ]
 [ 150.   112.    88.  ... -200.  -200.  -200. ]
 ...
 [1268.   972.  1074.  ... 1092.   770.   816. ]
 [  13.6   13.3   11.9 ...   26.9   28.3   28.5]
 [  48.9   47.7   54.  ...   18.3   13.5   13.1]]
(12, 9357)


In [0]:
Y = dfNumpy[:,12:13]
Y = np.transpose(Y)

In [586]:
print(Y)
print(np.shape(Y))

[[0.7578 0.7255 0.7502 ... 0.6406 0.5139 0.5028]]
(1, 9357)


In [0]:
#Returns tanh of Data

def tanh(data):
  data = np.tanh(data)
  return data

In [0]:
#Returns ReLU of Data

def relu(data):
    # data
    # data = np.where(data>0,data,0)
    return data

In [0]:
#Returns Sigmoid of Data

def sigmoid(data):
    data = 1 + np.exp(-data)
    data = 1/data
    return data

In [0]:
#ReLU Derivative
def reluDerivative(x):
  # print("########################################")
  # print("X before :")
  # print(x)
  # print(np.shape(x))
  # print("X after")
  # x[x<=0] = 0
  # x[x>0] = 1

  x.fill(1)
  # print(x)
  # print(np.shape(x))
  # print("#########################################")
  return x

In [0]:
#ReLU Backwards
def relu_backward(dA, cache):
  # print("ReLU")
  # print(cache)
  # print(np.shape(cache))
  # print("calling ReLU derivative")
  # reluDerivative(cache)
  # print(cache)
  dZ = np.multiply(dA, reluDerivative(cache))
  return dZ

In [0]:
#Sigmoid Derivative
def sigmoidDerivative(x):
  # print("%%%SigmoidDerivative%%")
  # print("X")
  # print(x)
  tempX = sigmoid(x)
  x = np.multiply(tempX, (1 - tempX))
  # print(x)
  # print("$$$$$$$$$$$$$$")
  return x

In [0]:
#Sigmoid Backwards
def sigmoid_backward(dA, cache):
  # print("^^^^^^^^^^^^")
  # print("Sigmoid")
  # print(dA)
  dZ = np.multiply(dA, sigmoidDerivative(cache)) 
  # print(dZ)
  # print("^^^^^^^^^^^^^^^^^^^^^^")
  return dZ

In [0]:
#Parameter initialization

    # Arguments:
    # layer_dims -- python array (list) containing the dimensions of each layer in the network
    
    # Returns:
    # parameters -- python dictionary containing your parameters "W1", "b1", ..., "WL", "bL":
    #                 Wl -- weight matrix of shape (layer_dims[l], layer_dims[l-1])
    #                 bl -- bias vector of shape (layer_dims[l], 1)

def initialize_parameters(layer_dims):
    parameters={}
    L = len(layer_dims)            # number of layers in the network

    for l in range(1, L):
        parameters['W' + str(l)] = np.random.randn(layer_dims[l], layer_dims[l-1]) * 0.01
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1)) 
        assert(parameters['W' + str(l)].shape == (layer_dims[l], layer_dims[l-1]))
        assert(parameters['b' + str(l)].shape == (layer_dims[l], 1))

    return parameters

In [0]:
    # Arguments:
    # layer_dims -- python array (list) containing the dimensions of each layer in our network
    
    # Returns:
    # parameters -- python dictionary containing your parameters "W1", "b1", ..., "WL", "bL":
    #                 Wl -- weight matrix of shape (layer_dims[l], layer_dims[l-1])
    #                 bl -- bias vector of shape (layer_dims[l], 1)

def initialize_parameters_deep(layer_dims):
    parameters = {}
    L = len(layer_dims)            # number of layers in the network

    for l in range(1, L):
        parameters['W' + str(l)] = np.random.rand(layer_dims[l], layer_dims[l-1]) * 0.01
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
        assert(parameters['W' + str(l)].shape == (layer_dims[l], layer_dims[l-1]))
        assert(parameters['b' + str(l)].shape == (layer_dims[l], 1))

    return parameters

In [0]:
    # The linear part of a layer's forward propagation.

    # Arguments:
    # A -- activations from previous layer : (size of previous layer, number of examples)
    # W -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    # b -- bias vector, numpy array of shape (size of the current layer, 1)

    # Returns:
    # Z -- the input of the activation function
    # cache -- a python tuple containing "A", "W" and "b"

def linear_forward(A, W, b):
    Z = np.dot(W,A) + b

    assert(Z.shape == (W.shape[0], A.shape[1]))
    cache = (A, W, b)
    
    return Z, cache

In [0]:
    # The forward propagation for the LINEAR->ACTIVATION layer

    # Arguments:
    # A_prev -- activations from previous layer : (size of previous layer, number of examples)
    # W -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    # b -- bias vector, numpy array of shape (size of the current layer, 1)
    # activation -- the activation to be used in this layer, stored as a text string: "sigmoid" or "relu" or "tanh"(will be coded later)

    # Returns:
    # A -- the output of the activation function
    # cache -- a python tuple containing "linear_cache" and "activation_cache";

def linear_activation_forward(A_prev, W, b, activation):
   
    if activation == "sigmoid":
        Z, linear_cache = linear_forward(A_prev, W, b)
        A = sigmoid(Z)
    
    elif activation == "relu":
        # print("A##########")
        # print(A_prev)
        # print("W#########")
        # print(W)
        # print("B########")
        # print(b)
        # print("##########")
        # print(np.shape(A_prev))
        # print(np.shape(W))
        # print(np.shape(b))
        # print(np.dot(W,A_prev))
        Z, linear_cache = linear_forward(A_prev, W, b)
        A = relu(Z)
        # print("#######Forward#######")
        # print(Z)
        # print()
        # print(A)
        # print("#####################")
    
    assert (A.shape == (W.shape[0], A_prev.shape[1]))
    cache = (linear_cache, Z)

    return A, cache

In [0]:

    # Forward propagation for the [Linear --> Sigmoid] * (L-1) -> [LINEAR->ReLU] computation
    
    # Arguments:
    # X -- data, numpy array of shape (input size, number of examples)
    # parameters -- output of initialize_parameters_deep()
    
    # Returns:
    # AL -- last post-activation value
    # caches -- list of caches containing:
    #             every cache of linear_activation_forward() (there are L-1 of them, indexed from 0 to L-1)

def L_model_forward(X, parameters):
    caches = []
    A = X
    L = int(len(parameters)/2)                 # number of layers in the neural network
    
    for l in range(1, L):
        A_prev = A 
        A, cache = linear_activation_forward(A_prev, parameters["W" + str(l)], parameters["b" + str(l)], "sigmoid")
        caches.append(cache)
    # print("^^^^^^^^^^^^^^^^^^^^^^^^^^^")
    # print("L_model_forward  parameters")
    # print(parameters)
    AL, cache = linear_activation_forward(A, parameters["W" + str(L)], parameters["b" + str(L)], "relu")

    # print("^^^^^^^^^^^^^^^^^^^^^^^^^^^")
    # print("L_model_forward AL")
    # print(AL)
    # print(np.count_nonzero(AL))

    # print("%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    caches.append(cache)
    
    assert(AL.shape == (1,X.shape[1]))
            
    return AL, caches

In [0]:
    #Cost Function
    #Squared Error

    # Arguments:
    # AL -- probability vector corresponding to predictions, shape (1, number of examples)
    # Y -- true value

    # Returns:
    # cost -- cross-entropy cost

def compute_cost(AL, Y):  
    m = Y.shape[1]

    cost = np.mean(np.square(Y - AL) )
    
    cost = np.squeeze(cost)      # To make sure your cost's shape is what we expect (e.g. this turns [[17]] into 17).
    assert(cost.shape == ())
    
    return cost

In [0]:
    # The Linear portion of backward propagation for a single layer (layer l)

    # Arguments:
    # dZ -- Gradient of the cost with respect to the linear output (of current layer l)
    # cache -- tuple of values (A_prev, W, b) coming from the forward propagation in the current layer

    # Returns:
    # dA_prev -- Gradient of the cost with respect to the activation (of the previous layer l-1), same shape as A_prev
    # dW -- Gradient of the cost with respect to W (current layer l), same shape as W
    # db -- Gradient of the cost with respect to b (current layer l), same shape as b

def linear_backward(dZ, cache):

    A_prev, W, b = cache
    m = A_prev.shape[1]

    dW = (1/m) * np.dot(dZ, np.transpose(A_prev))
    db = (1/m) * np.sum(dZ,axis = 1,keepdims = True)
    dA_prev = np.dot(np.transpose(W), dZ)
   
    assert (dA_prev.shape == A_prev.shape)
    assert (dW.shape == W.shape)
    assert (db.shape == b.shape)
    
    return dA_prev, dW, db

In [0]:
    # The backward propagation for the LINEAR->ACTIVATION layer.
    
    # Arguments:
    # dA -- post-activation gradient for current layer l 
    # cache -- tuple of values (linear_cache, activation_cache) we store for computing backward propagation efficiently
    # activation -- the activation to be used in this layer, stored as a text string: "sigmoid" or "relu"
    
    # Returns:
    # dA_prev -- Gradient of the cost with respect to the activation (of the previous layer l-1), same shape as A_prev
    # dW -- Gradient of the cost with respect to W (current layer l), same shape as W
    # db -- Gradient of the cost with respect to b (current layer l), same shape as b

def linear_activation_backward(dA, cache, activation):

    linear_cache, activation_cache = cache
    
    if activation == "relu":
        dZ = relu_backward(dA, activation_cache)
        dA_prev, dW, db = linear_backward(dZ, linear_cache)
        
    elif activation == "sigmoid":
        dZ = sigmoid_backward(dA, activation_cache)
        dA_prev, dW, db = linear_backward(dZ, linear_cache)
   
    return dA_prev, dW, db

In [0]:
# The backward propagation for the [LINEAR->Sigmoid] * (L-1) -> [LINEAR -> ReLU] group
    
#     Arguments:
#     AL -- Output of the forward propagation (L_model_forward())
#     Y -- True Value
#     caches -- list of caches containing:

    
#     Returns:
#     grads -- A dictionary with the gradients
#              grads["dA" + str(l)] = ... 
#              grads["dW" + str(l)] = ...
#              grads["db" + str(l)] = ... 

def L_model_backward(AL, Y, caches):

    grads = {}
    L = len(caches) # the number of layers
    m = AL.shape[1]
    Y = Y.reshape(AL.shape) # after this line, Y is the same shape as AL
    
    # Initializing the backpropagation
    dAL = -(Y - AL) # derivative of cost with respect to AL
    
    # Lth layer (ReLU -> LINEAR) gradients. Inputs: "dAL, current_cache". Outputs: "grads["dAL-1"], grads["dWL"], grads["dbL"]

    current_cache = caches[L-1]
    grads["dA" + str(L-1)], grads["dW" + str(L)], grads["db" + str(L)] = linear_activation_backward(dAL, current_cache, "relu")
    
    # print("##########L_model_bk")
    # print(grads["dA" + str(L-1)])
    # print(grads["dW" + str(L)])
    # print(grads["db" + str(L)])
    # print("%%%%%%%%%%%%%%%%%%%%%%%")
    
    # Loop from l=L-2 to l=0
    for l in reversed(range(L-1)):
        # lth layer: (Sigmoid -> LINEAR) gradients.
        # Inputs: "grads["dA" + str(l + 1)], current_cache". Outputs: "grads["dA" + str(l)] , grads["dW" + str(l + 1)] , grads["db" + str(l + 1)] 

        current_cache = caches[l]
        dA_prev_temp, dW_temp, db_temp = linear_activation_backward(grads["dA" + str(l+1)], current_cache, "sigmoid")
        grads["dA" + str(l)] = dA_prev_temp
        grads["dW" + str(l + 1)] = dW_temp
        grads["db" + str(l + 1)] = db_temp

    return grads

In [0]:
    # Update parameters using gradient descent
    
    # Arguments:
    # parameters -- python dictionary containing your parameters 
    # grads -- python dictionary containing your gradients, output of L_model_backward
    
    # Returns:
    # parameters -- python dictionary containing your updated parameters 
    #               parameters["W" + str(l)] = ... 
    #               parameters["b" + str(l)] = ...

def update_parameters(parameters, grads, learning_rate):

    L = int(len(parameters)/2)  # number of layers in the neural network

    for l in range(L):
        parameters["W" + str(l+1)] = parameters["W" + str(l+1)] - ( learning_rate * grads["dW" + str(l+1)] ) 
        parameters["b" + str(l+1)] = parameters["b" + str(l+1)] - ( learning_rate * grads["db" + str(l+1)] ) 

    return parameters

In [0]:
### CONSTANTS ###
layers_dims = [12, 10, 7, 5, 1] #  4-layer model

In [0]:
    # Implements a L-layer neural network: [LINEAR->RELU]*(L-1)->LINEAR->SIGMOID.
    
    # Arguments:
    # X -- data, numpy array of shape (num_px * num_px * 3, number of examples)
    # Y -- true "label" vector (containing 0 if cat, 1 if non-cat), of shape (1, number of examples)
    # layers_dims -- list containing the input size and each layer size, of length (number of layers + 1).
    # learning_rate -- learning rate of the gradient descent update rule
    # num_iterations -- number of iterations of the optimization loop
    # print_cost -- if True, it prints the cost every 100 steps
    
    # Returns:
    # parameters -- parameters learnt by the model. They can then be used to predict.

def L_layer_model(X, Y, layers_dims, learning_rate = 0.009, num_iterations = 3000, print_cost=False):#lr was 0.009

    costs = []                         # keep track of cost
    
    # Parameters initialization. (≈ 1 line of code)
    parameters = initialize_parameters_deep(layers_dims)
    
    # Loop (gradient descent)
    for i in range(0, num_iterations):

        # print("%%%%%%%%%%%%%%%%%%")
        # print(X)
        # Forward propagation: [LINEAR -> RELU]*(L-1) -> LINEAR -> SIGMOID.
        AL, caches = L_model_forward(X, parameters)
        
        # print("&&&&&&&&&&&&&&&&")
        # print(AL)
        # print("&&&&&&&&&&&&&&&&")

        # Compute cost.
        cost = compute_cost(AL, Y)
    
        # Backward propagation.
        grads = L_model_backward(AL, Y, caches)
 
        # Update parameters.
        parameters = update_parameters(parameters, grads, learning_rate)
                
        # Print the cost every 100 training example
        if print_cost and i % 100 == 0:
            print ("Cost after iteration %i: %f" %(i, cost))
        if print_cost and i % 100 == 0:
            costs.append(cost)
            
    
    return parameters

In [612]:
parameters = L_layer_model(X, Y, layers_dims, num_iterations = 2500, print_cost = True)

Cost after iteration 0: 1566.007507
Cost after iteration 100: 1500.955479
Cost after iteration 200: 1220.985789
Cost after iteration 300: 869.290789
Cost after iteration 400: 618.428668
Cost after iteration 500: 441.051334
Cost after iteration 600: 314.974943
Cost after iteration 700: 225.087664
Cost after iteration 800: 160.911760
Cost after iteration 900: 115.063392
Cost after iteration 1000: 82.298284
Cost after iteration 1100: 58.879089
Cost after iteration 1200: 42.138346
Cost after iteration 1300: 30.170823
Cost after iteration 1400: 21.615201
Cost after iteration 1500: 15.498583
Cost after iteration 1600: 11.125576
Cost after iteration 1700: 7.999096
Cost after iteration 1800: 5.763794
Cost after iteration 1900: 4.165632
Cost after iteration 2000: 3.022995
Cost after iteration 2100: 2.206039
Cost after iteration 2200: 1.621934
Cost after iteration 2300: 1.204312
Cost after iteration 2400: 0.905719
